-- CARTS
create table IF NOT EXISTS public.carts (
  id integer generated by default as identity not null,
  user_id uuid not null,
  product_version_id integer not null,
  quantity integer not null,
  size text not null,
  added_at timestamp with time zone null default now(),
  products integer null,
  serial text null,
  title text null,
  base_price integer null,
  total_price integer null,
  constraint carts_pkey primary key (id),
  constraint carts_id_key unique (id),
  constraint carts_product_version_id_fkey foreign KEY (product_version_id) references product_versions (id) on delete CASCADE,
  constraint carts_products_fkey foreign KEY (products) references products (id),
  constraint carts_user_id_fkey foreign KEY (user_id) references auth.users (id),
  constraint carts_quantity_check check ((quantity > 0))
) TABLESPACE pg_default;

-- CARTS
CREATE TABLE IF NOT EXISTS carts (
  id SERIAL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id),
  product_version_id INTEGER NOT NULL REFERENCES product_versions(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  size TEXT NOT NULL,
  added_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);